//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public int AtencionId { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public Nullable<System.TimeSpan> Desde { get; set; }
        public Nullable<System.TimeSpan> Hasta { get; set; }
        public Nullable<int> DiaId { get; set; }
    
        public virtual DiasSemana DiasSemana { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
