//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica_profesionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinica_profesionales()
        {
            this.Clinica_profesinales_especialidad = new HashSet<Clinica_profesinales_especialidad>();
        }
    
        public int id_PC { get; set; }
        public Nullable<int> id_profesional { get; set; }
        public Nullable<int> id_clinica { get; set; }
    
        public virtual Clinica Clinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinica_profesinales_especialidad> Clinica_profesinales_especialidad { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
