//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica_profesinales_especialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinica_profesinales_especialidad()
        {
            this.sucursales_profesionales_especialidades = new HashSet<sucursales_profesionales_especialidades>();
        }
    
        public int id_cpe { get; set; }
        public Nullable<int> id_cp { get; set; }
        public Nullable<int> id_especialidad { get; set; }
    
        public virtual Clinica_profesionales Clinica_profesionales { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales_profesionales_especialidades> sucursales_profesionales_especialidades { get; set; }
    }
}
