//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int PacienteID { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Email { get; set; }
        public Nullable<int> Numero_credencial { get; set; }
        public Nullable<int> ObraId { get; set; }
        public string photopath { get; set; }
    
        public virtual obra_social obra_social { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
