//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Atencion = new HashSet<Atencion>();
            this.sucursales_profesionales_especialidades = new HashSet<sucursales_profesionales_especialidades>();
        }
    
        public int SucursalId { get; set; }
        public Nullable<int> ClinicaId { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public string Photopath { get; set; }
        public string Calle { get; set; }
        public string Altura { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Consultorios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        public virtual Clinica Clinica { get; set; }
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursales_profesionales_especialidades> sucursales_profesionales_especialidades { get; set; }
    }
}
