//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public string Clave { get; set; }
        public int TipoUsuarioId { get; set; }
        public int RolId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Creado { get; set; }
        public System.DateTime Modificado { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
